AWSTemplateFormatVersion: '2010-09-09'
Description: ECS stack

Parameters:
  PrivateSubnet1:
    Type: String
  PrivateSubnet2:
    Type: String
  ECSSecurityGroup:
    Type: String
  TargetGroupArn:
    Type: String

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: coal-chatbot-cluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: coal-chatbot-task
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::084658101526:role/coal-chatbot-ecs-execution-role
      ContainerDefinitions:
        - Name: coal-chatbot-container
          Image: 084658101526.dkr.ecr.ap-south-1.amazonaws.com/coal-chatbot:latest
          Essential: true
          PortMappings:
            - ContainerPort: 5000

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      LoadBalancers:
        - ContainerName: coal-chatbot-container
          ContainerPort: 5000
          TargetGroupArn: !Ref TargetGroupArn