AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch log group

Resources:
  ChatbotLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/coal-chatbot
      RetentionInDays: 7